version: '3.4'

services:
  sample.restaurant.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 54576:80
      - 54577:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  database:
    container_name: lewee_sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 5434:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=<YourStrong@Passw0rd!>
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - lewee-network
