name: Pack Test

on:
  workflow_dispatch:

jobs:
  packTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine Version
        id: version
        uses: ./.github/actions/get-version@latest
      - name: Set Version
        uses: ./.github/actions/set-version
        with:
          version: $steps.version.outputs.latest-tag
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*
      - name: Pack
        run: dotnet pack ./pack.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.latest-tag }}